# Generated by Django 3.0.6 on 2021-09-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
