# Generated by Django 3.0.6 on 2021-09-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_snippets', '0002_auto_20210912_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_title', to='text_snippets.Title'),
        ),
        migrations.AlterField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
